@extends('layouts/main')


@section('content')
<!-- start loader -->
   <div id="pageloader-overlay" class="visible incoming"><div class="loader-wrapper-outer"><div class="loader-wrapper-inner" ><div class="loader"></div></div></div></div>
   <!-- end loader -->

   
<!-- Start wrapper-->
<div id="wrapper">

 <div class="loader-wrapper">
  <div class="lds-ring">
	  <div class="card terms-view mx-auto my-5">
		  <div class="card-body">
        <div class="text-center pb-4">
          <img src="{{ asset('images/logo-icon.png')}}" alt="logo icon">
        </div>
				{{ csrf_field() }}
	
			  {{-- <input type="" name="_token" value="{{ csrf_token() }}"> --}}
     <!--Start Back To Top Button-->
      <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>

      <p class="pt-2">
      Terms & Conditions
  PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICES (DEFINED BELOW) ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER.
  Terms of Use
  Effective date: August 20, 2020 
  Welcome to Changa App. Please read on to learn the rules and restrictions that govern your use of our website(s), products, services and applications (the “Services”). If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at support@changaapp.com.
  These Terms of Use (the “Terms”) are a binding contract between you and Changa App Inc (“Company,” “we” and “us”). The Terms describe both your rights and your obligations in connection with your use of the Services. It is important that you read and understand these Terms, as they are legally binding.   
  You must agree to and accept all of the Terms, or you don't have the right to use the Services. Your using the Services in any way means that you agree to all of the Terms, and the Terms will remain in effect while you use the Services. These Terms include the provisions in this document, as well as those in the Privacy Policy.
  Please note that certain Services may require that you agree to additional terms prior to use (“Additional Terms”).  In that event, those Additional Terms will be considered to form and be a part of these Terms, and in case of any conflict between these Terms and any Additional Terms, the Additional Terms shall prevail with regard to the particular Service they are associated with.
  IMPORTANT INFORMATION REGARDING THE SERVICES. PLEASE READ. 
  The Services have been designed to provide users with information about techniques that can be used to potentially enhance the quality of psychedelic and/or consciousness-expanding activities.
  Psychedelic and/or consciousness-expanding experiences can be achieved through a number of legal techniques, such as meditation, breathwork, use of legal or medically prescribed drugs, such as ketamine, psilocybin or natural supplements in controlled circumstances with appropriate supervision. The Services are designed exclusively for psychedelic and/or consciousness-expanding experiences and practices that are legal in the jurisdiction in which you reside. 
  THE SERVICES ARE NOT DESIGNED TO BE, AND SHOULD NOT BE, USED IN CONJUNCTION WITH ANY ILLEGAL DRUGS OR ACTIVITIES. 
  Before using the Services, you agree to research, understand and comply with the laws in your jurisdiction in respect of psychedelic and/or consciousness-expanding drugs or natural products, as well as the risks of using those products, and potential interactions with other medications. You hereby acknowledge that you should consult a licensed, certified medical and/or mental healthcare professional prior to beginning or modifying any program that you undertake.
  PSYCHEDELIC AND/OR CONSCIOUSNESS-EXPANDING TECHNIQUES CARRY INHERENT RISKS OF MENTAL AND PHYSICAL INJURY OR DEATH AND ARE NOT SUITABLE FOR EVERYONE.
  By using the Services, you voluntarily assume all known and unknown risks associated with these activities even if caused in whole or in part by the Services, and expressly agree to release Company from any liability for health issues or injuries that occur as a result of participation in activity related to or used in association with the Services. 
  Will these Terms ever change?
  We are constantly trying to improve our Services, so these Terms may need to change along with the Services. We reserve the right to change the Terms at any time, but if we do, we will bring it to your attention by placing a notice on our website or within the application(s), by sending you an email, and/or by some other means. Revisions to these Terms will become effective on the date set forth in our notice. It is your responsibility to review the most current version of these Terms by visiting our website. 
  If you don't agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes.
  Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.
  What about my privacy?
  We take the privacy of our users very seriously.  For our current Privacy Policy, please click here.
  The Children's Online Privacy Protection Act (“COPPA”) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13. We do not knowingly collect or solicit personally identifiable information from children under 13; if you are a child under 13, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn we have collected personal information from a child under 13, we will delete that information as quickly as possible. If you believe that a child under 13 may have provided us personal information, please contact us at support@changaapp.com.
  What are the basics of using Changa App?
  You understand that the Services are not medical, therapeutic or healthcare services, and that no physician-patient relationship exists.
  YOU HEREBY AGREE THAT, BEFORE USING THE SERVICES, YOU WILL CONSULT A MEDICAL AND/OR MENTAL HEALTHCARE PROFESSIONAL. 
  The Company itself does not offer, and the Services do not constitute, medical or healthcare advice or services and no physician-patient relationship with the Company or any of its employees, officers, or agents is created or implied by you accessing or using the Service. The information and materials provided through the Services are provided purely for informational purposes. You should always seek the advice of a physician or other qualified mental healthcare provider who you personally know before starting, stopping, or modifying any consciousness expansion activities.
  You understand that the Services are not a substitute for emergency services.
  THE SERVICES SHOULD NEVER BE USED AS A SUBSTITUTE FOR EMERGENCY CARE.
  If you are in a life-threatening situation, feel that you are a danger to yourself or others, or are having thoughts of suicide, please call the 24-hr National Suicide Prevention Lifeline at 1.800.273.8255 and notify the relevant authorities. Your call will be routed to the crisis center near you. If your issue is an emergency, call 911 immediately or go to your nearest emergency room. You acknowledge and understand that you should never delay seeking treatment from your primary care physician or other qualified healthcare professional.
  You may be required to sign up for an account, and select a password and user name (“Company User ID”). You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your Company User ID a name that you don't have the right to use, or another person's name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission.
  You represent and warrant that you are an individual of legal age to form a binding contract.
  You will only use the Services for your own internal, personal, non-commercial use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren't authorized to use the Services. We can't and won't be responsible for your using the Services in a way that breaks the law.
  You will not share your account or password with anyone, and you must protect the security of your account and your password. You're solely responsible for maintaining the confidentiality of your Account and password and for restricting access to your devices, and you agree that you are solely responsible for any activity associated with your account.
  Your use of the Services is subject to the following additional restrictions:
  You represent, warrant, and agree that you will not contribute any Content or User Submission (each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that:
  1.	Infringes or violates the intellectual property rights or any other rights of anyone else (including Company) or removes any copyright or other proprietary notices on or in relation to the Content or any part thereof;
  2.	Violates any local, provincial, state, national or international law or regulation, including any applicable export control laws, or violates any court order, arbitral order, or lawful order of any governmental authority;
  3.	Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;
  4.	Jeopardizes the security of your account or anyone else's (such as allowing someone else to log in to the Services as you);
  5.	Attempts, in any manner, to disable or circumvent any access control or related process or procedure established with respect to the Services, or attempt to gain unauthorized access to any Services or obtain the password, account, or other security information from any other user;
  6.	Violates the security of any computer network, or cracks any passwords or security encryption codes;
  7.	Runs Maillist, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services' infrastructure);
  8.	“Crawls,” “scrapes,” “spiders,” mines or extracts any page, data, or portion of or relating to other users, the Services or Content (through use of manual or automated means);
  9.	Copies or stores any significant portion of the Content, makes Content available to anyone, permits anyone to access Content, or license, sublicense, sell, resell, publish, republish, transfer, assign, distribute, rent, lease, time-share, copy or otherwise commercially exploit the Services or Content in any way except in accordance with these Terms; 
  10.	Would expose Company or any of our users to harm, or encourage any user of the Services to act in violation of these Terms; or 
  11.	Decompiles, reverse engineers, tamper with or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.
  A violation of any of the foregoing is grounds for immediate termination of your right to use or access the Services without notice.
  What are my rights in the Services?
  The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won't use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else's (including Company's) rights.
  You understand that Company owns the Services. You won't modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services.
  The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn't mean that all the restrictions above don't apply – they do!
  Do I have to grant any licenses to Company or to other users?
  Anything you post, upload, share, store, or otherwise provide through the Services is your “User Submission.” In its current form, nothing on the Services will be shared with third parties or other users. However, in the future, certain functionality may result in some of your User Submissions to be viewable by other users. In order to display your User Submissions on the Services, and to allow other users to enjoy them (where applicable), you grant us certain rights in those User Submissions. Please note that all of the following licenses are subject to our Privacy Policy to the extent they relate to User Submissions that are also your personally-identifiable information.
  For all User Submissions, you hereby grant Company a license to translate, modify (for technical purposes, for example making sure your content is viewable on an iPhone as well as a computer) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services, as described in more detail below. This is a license only – your ownership in User Submissions is not affected.
  If you store a User Submission in your own personal Company account, in a manner that is not viewable by any other user except you (a “Personal User Submission”), you grant Company the license above, as well as a license to display, perform, and distribute your Personal User Submission for the sole purpose of making that Personal User Submission accessible to you and providing the Services necessary to do so.
  If you share a User Submission only in a manner that only certain specified users can view (for example, a private message to one or more other users)(a “Limited Audience User Submission”), then you grant Company the licenses above, as well as a license to display, perform, and distribute your Limited Audience User Submission for the sole purpose of making that Limited Audience User Submission accessible to such other specified users, and providing the Services necessary to do so. Also, you grant such other specified users a license to access that Limited Audience User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.
  If you share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view, or if you provide us (in a direct email or otherwise) with any feedback, suggestions, improvements, enhancements, and/or feature requests relating to the Services (each of the foregoing, a “Public User Submission”), then you grant Company the licenses above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of making that Public User Submission accessible to all Company users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with the Services and/or otherwise in connection with Company's business. Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.
  You agree that the licenses you grant are royalty-free, perpetual, sublicensable, irrevocable, and worldwide.
  Finally, you understand and agree that Company, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so.
  What if I see something on the Services that infringes my copyright?
  You may have heard of the Digital Millennium Copyright Act (the “DMCA”), as it relates to online service providers, like Company, being asked to remove material that allegedly violates someone's copyright. We respect others' intellectual property rights, and we reserve the right to delete or disable Content alleged to be infringing, and to terminate the accounts of repeat alleged infringers. To learn more about the DMCA, click here. In accordance with the DMCA, we've adopted the policy below toward copyright infringement.
  Procedure for Reporting Copyright Infringements.  If you believe that material or content residing on or accessible through the Services infringes your copyright (or the copyright of someone whom you are authorized to act on behalf of), please send a notice of copyright infringement containing the following information to the Company's Designated Agent to Receive Notification of Claimed Infringement (our “Designated Agent,” whose contact details are listed below):
  •	A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright that has been allegedly infringed;
  •	Identification of works or materials being infringed;
  •	Identification of the material that is claimed to be infringing including information regarding the location of the infringing materials that the copyright owner seeks to have removed, with sufficient detail so that Company is capable of finding and verifying its existence;
  •	Contact information about the notifier including address, telephone number and, if available, email address;
  •	A statement that the notifier has a good faith belief that the material identified in (1)(c) is not authorized by the copyright owner, its agent, or the law; and
  •	A statement made under penalty of perjury that the information provided is accurate and the notifying party is authorized to make the complaint on behalf of the copyright owner.
  Once Proper Bona Fide Infringement Notification is Received by the Designated Agent. Upon receipt of a proper notice of copyright infringement, we reserve the right to:
  •	remove or disable access to the infringing material;
  •	notify the content provider who is accused of infringement that we have removed or disabled access to the applicable material; and
  •	terminate such content provider's access to the Services if he or she is a repeat offender. 
  Procedure to Supply a Counter-Notice to the Designated Agent. If the content provider believes that the material that was removed (or to which access was disabled) is not infringing, or the content provider believes that it has the right to post and use such material from the copyright owner, the copyright owner's agent, or, pursuant to the law, the content provider may send us a counter-notice containing the following information to the Designated Agent:
  A physical or electronic signature of the content provider;
  •	Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or disabled;
  •	A statement that the content provider has a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material; and
  •	Content provider's name, address, telephone number, and, if available, email address, and a statement that such person or entity consents to the jurisdiction of the Federal Court for the judicial district in which the content provider's address is located, or, if the content provider's address is located outside the United States, for any judicial district in which Company is located, and that such person or entity will accept service of process from the person who provided notification of the alleged infringement.
  If a counter-notice is received by the Designated Agent, Company may, in its discretion, send a copy of the counter-notice to the original complaining party informing that person that Company may replace the removed material or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider accused of committing infringement, the removed material may be replaced or access to it restored in 10 to 14 business days or more after receipt of the counter-notice, at Company's discretion.
  Please contact Company's Designated Agent at the following address: support@changaapp.com
  Who is responsible for what I see and do on the Services?
  You acknowledge that certain consciousness-expanding activities, including the use of herbal supplements or legal prescription medications, involve risks, including risk of bodily injury or death, and you expressly acknowledge and agree that assume those risks. You hereby acknowledge that you should consult a licensed, certified medical and/or mental healthcare professional prior to beginning or modifying any program that you undertake. The Company makes no representations, and has no obligation with respect to (a) the appropriateness of your engaging in consciousness-expanding activities; (b) the results (or lack of results) obtained by your use of the Services; and (c) any health-related matters arising in connection with your use the Services.
  Any information or content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such content originated, and you access all such information and content at your own risk, and we aren't liable for any errors or omissions in that information or content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can't guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.
  You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services.
  The Services may contain links or connections to third party websites or services that are not owned or controlled by Company. When you access third party websites or use third party services, you accept that there are risks in doing so, and that Company is not responsible for such risks. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third party website or service that you visit or utilize.
  Company has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites or by any third party that you interact with through the Services. In addition, Company will not and cannot monitor, verify, censor or edit the content of any third party site or service. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third party website or service.
  Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that Company shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.
  If there is a dispute between participants on this site, or between users and any third party, you agree that Company is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release Company, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services.
  If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: “A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which, if known by him or her must have materially affected his or her settlement with the debtor.”
  Will Company ever change the Services?
  We're always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We'll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn't always practical. Similarly, we reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.
  Does Changa cost anything?
  Certain elements and features of the Services are free, but we may charge for some features of the Services and reserve the right to charge for certain additional Services in the future. We will notify you before any Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services. Before using any portions of the Service that are available for a fee, you will be required to select a payment plan and provide Company information regarding your credit card or other payment instrument. You represent and warrant to Company that such information is true and that you are authorized to use the payment instrument. You will promptly update your account information with any changes (for example, a change in your billing address or credit card expiration date) that may occur. You agree to pay us the amount that is specified in the payment plan in accordance with the terms of such plan and these Terms. You hereby authorize us to bill your payment instrument in advance on a periodic basis in accordance with the terms of the applicable payment plan until you terminate your account, and you further agree to pay any charges so incurred. If you dispute any charges you must let us know within sixty (60) days after the date that Company charges you. We reserve the right to change our prices. If we do change prices, we will provide notice of the change on the site, in the Services, or in an email to you, at our option, at least 30 days before the change is to take effect. Your continued use of the Services after the price change becomes effective constitutes your agreement to pay the changed amount. You shall be responsible for all taxes associated with the Services other than U.S. taxes based on Company's net income.
  What if I want to stop using Changa?
  Simply delete your account and uninstall the App (as such term is defined below) from your mobile device. Also, please refer to our Privacy Policy, as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.
  We may terminate (or suspend access to) your use of the Services or your account, for any reason in our discretion, including your breach of these Terms, and we reserve the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.
  Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account.
  Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us.
  I use the Changa App (the “App”)– should I know anything about that?
  The App is made available through the Apple App Store, the Google Play Store, or other distribution channels (“Distribution Channels”).  If you obtain such App through a Distribution Channel, you may be subject to additional terms of the Distribution Channel.  These Terms of Service are between you and us only, and not with the Distribution Channel.  To the extent that you utilize any other third-party products and services in connection with your use of our Services, you agree to comply with all applicable terms of any agreement for such third party products and services.
  With respect to the App that is made available for your use in connection with an Apple-branded product (such Software, “Apple-Enabled Software”), in addition to the other terms and conditions set forth in these Terms of Service, the following terms and conditions apply:
  You acknowledge that these Terms are between you and us only, and not with Apple Inc. (“Apple”), and that as between us and Apple, we, not Apple, is solely responsible for the Apple-Enabled Software and the content thereof.
  You may not use the Apple-Enabled Software in any manner that is in violation of or inconsistent with the Usage Rules set forth for Apple-Enabled Software in, or otherwise be in conflict with, the App Store Terms of Service.
  Your license to use the Apple-Enabled Software is limited to a non-transferable license to use the Apple-Enabled Software on an iOS Product that you own or control, as permitted by the Usage Rules set forth in the App Store Terms of Service.
  Apple has no obligation whatsoever to provide any maintenance or support services with respect to the Apple-Enabled Software. 
  Apple is not responsible for any product warranties, whether express or implied by law. In the event of any failure of the Apple-Enabled Software to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the Apple-Enabled Software to you, if any; and, to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the Apple-Enabled Software, or any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty, which will be Company's sole responsibility, to the extent it cannot be disclaimed under applicable law.
  You acknowledge that we, not Apple, are responsible for addressing any claims of you or any third party relating to the Apple-Enabled Software or your possession and/or use of that Apple-Enabled Software, including, but not limited to: (i) product liability claims; (ii) any claim that the Apple-Enabled Software fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.  
  In the event of any third party claim that the Apple-Enabled Software or the end-user's possession and use of that Apple-Enabled Software infringes that third party's intellectual property rights, as between us and Apple, we, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim.
  You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.
  If you have any questions, complaints or claims with respect to the Apple-Enabled Software, they should be directed to Company as follows:
  Changa App Support
  937 Country Club Rd.,
  Lake Oswego, OR
  97034
  You acknowledge and agree that Apple, and Apple's subsidiaries, are third party beneficiaries of these Terms with respect to the Apple-Enabled Software, and that, upon your acceptance of the terms and conditions of these Terms of Service, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms of Service against you with respect to the Apple-Enabled Software as a third party beneficiary thereof.
  What else do I need to know?
  The Content and User Submissions should not be considered medical or mental health advice or a replacement or substitute for medical or mental health advice. You should always talk to an appropriately qualified health care professional for diagnosis and treatment, including information regarding which medications or treatment may be appropriate for you. None of the Content and/or User Submissions represents or warrants that any particular medication or treatment (or lack thereof) is safe, appropriate, or effective for you.
  Warranty Disclaimer. 
  Neither us, or our licensors or suppliers, make any representations or warranties concerning any content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services. We make no representations or warranties with respect to professional qualifications, expertise, or quality of work and in no event shall we be liable to you for any decision made or action taken in reliance on any content available through the Services. We (and our licensors and suppliers) make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services.
  Products and services purchased or offered (whether or not following such recommendations and suggestions) through the Services are provided “AS IS” and without any warranty of any kind from Company or others (unless, with respect to such others only, provided expressly and unambiguously in writing by a designated third party for a specific product). THE SERVICES AND CONTENT ARE PROVIDED BY US (AND OUR LICENSORS AND SUPPLIERS) ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE SERVICES OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO SOME OR ALL OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. 
  Limitation of Liability.
  TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) WILL WE (OR OUR LICENSORS OR SUPPLIERS) BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, DAMAGE TO HARDWARE, SOFTWARE OR SYSTEMS, EVEN IF THE POTENTIAL FOR SUCH DAMAGE WAS PREVIOUSLY DISCLOSED OR REASONABLY FORESEEABLE IN THE CIRCUMSTANCES, OR (B) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) \$100 OR (II) THE AMOUNTS PAID BY YOU TO US IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM, (C) ANY DEATH OR BODILY INJURY THAT YOU SUFFER, OR THAT YOU CAUSE TO ANY THIRD PARTY, IN CONNECTION WITH YOUR USE OF THE SERVICE OR ANY ACTIVITY YOU UNDERTAKE IN CONNECTION WITH YOUR USE OF THE SERVICE, OR (D) ANY MATTER BEYOND OUR REASONABLE CONTROL. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OR ALL OF THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.
  Indemnity. To the fullest extent allowed by applicable law, You agree to indemnify and hold Company, its affiliates, officers, agents, employees, and partners harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys' fees) arising from or in any way related to any third party claims relating to:
  a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. In the event of such a claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).
  Assignment. You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without our prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.
  Choice of Law; Arbitration.
  Choice of Law: This Agreement shall be governed by, and construed in accordance with, the laws of the State of Oregon, excluding its conflicts of law principles.
  Arbitration: All claims and disputes arising under or relating to this Agreement are to be settled by binding arbitration in the State of Oregon. An award of arbitration may be confirmed in a court of competent jurisdiction. The arbitration shall be conducted on a confidential basis pursuant to the Commercial Arbitration Rules of the American Arbitration Association. Any decision or award as a result of any such arbitration proceeding shall be in writing and shall provide an explanation for all conclusions of law and fact and shall include the assessment of costs, expenses, and reasonable attorneys' fees.
  Please note that by agreeing to this provision, you are waiving your right to a jury trial and you are agreeing to resolve any disputes through binding arbitration. This provision does not prevent either party from seeking injunctive relief in a court of competent jurisdiction.
  Before initiating any arbitration process, you are encouraged to resolve disputes by negotiation. If the dispute cannot be resolved by negotiation, either party may commence arbitration.
  Electronic Communication 
  When you visit our website, interact with our applications, or send e-mails to us, you are communicating with us electronically. You consent to receive communications from us electronically for the purpose of providing Services, including soliciting feedback or advising you of any new or Additional Services. You agree that all agreements, notices, disclosures, or other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. 
  Miscellaneous.
  You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the we may, in our sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise or enforce, in any way, any right or provision herein shall not be deemed a waiver of any further rights or provision hereunder in that or any other circumstances. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You agree that these Terms are the complete and exclusive statement of the mutual understanding between you and us in respect of the Services, and that it supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms.
      </p>
    <!--End Back To Top Button-->
</div>
  </div>
  </div>
  </div>
	
	<!--start color switcher-->
   <div class="right-sidebar">
    <div class="switcŽer-icon">
      <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
    </div>
    <div class="right-sidebar-content">

      <p class="mb-0">Gaussion Texture</p>
      <hr>
      
      <ul class="switcher">
        <li id="theme1"></li>
        <li id="theme2"></li>
        <li id="theme3"></li>
        <li id="theme4"></li>
        <li id="theme5"></li>
        <li id="theme6"></li>
      </ul>

      <p class="mb-0">Gradient Background</p>
      <hr>
      
      <ul class="switcher">
        <li id="theme7"></li>
        <li id="theme8"></li>
        <li id="theme9"></li>
        <li id="theme10"></li>
        <li id="theme11"></li>
        <li id="theme12"></li>
		<li id="theme13"></li>
        <li id="theme14"></li>
        <li id="theme15"></li>
      </ul>
      
     </div>
   </div>
  <!--end color switcher-->
	
	</div><!--wrapper-->
	
{{-- @include('panels/script') --}}

@endsection
